name: Test_Shapes_First_Submission

on:
  workflow_dispatch:

jobs:
  test_compilation:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY

      - name: Clear cache
        if: steps.setup-cache.outputs.cache-hit == 'true'
        run: |
          cd ~/github_actions_cache
          rmdir *
          del *

      
      - name: Download jar files
        run: |
          wget -O processing_core.jar "https://github.com/Nathaniel-github/APCSActionTesting/blob/main/jars/processing_core.jar?raw=true"
          wget -O kTesting.jar "https://github.com/kchandra423/KTesting/blob/master/out/artifacts/KTesting_jar/KTesting.jar?raw=true"
          wget -O ShapesTest.java "https://raw.githubusercontent.com/Nathaniel-github/APCSActionTesting/main/ShapesLab/src/ShapesTest.java"
      
      - name: Compile the code
        run: javac -cp ".;processing_core.jar;kTesting.jar" *.java

      - name: Move files into github_actions_cache
        run: |
          cd ..
          cd ..
          cd ..
          dir
          move "$GITHUB_REPOSITORY" "~/github_actions_cache"

  test_rectangle_exists:
    runs-on: self-hosted
    needs: test_compilation
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsRectangle
          
  test_rectangle_no_arg_constructor_setup:
    runs-on: self-hosted
    needs: test_rectangle_exists
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsNoArgConstructorRectangle

  test_rectangle_constructor_setup:
    runs-on: self-hosted
    needs: test_rectangle_exists
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsConstructorRectangle

  test_circle_exists:
    runs-on: self-hosted
    needs: test_compilation
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsCircle

  test_circle_no_arg_constructor_setup:
    runs-on: self-hosted
    needs: test_circle_exists
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsNoArgConstructorCircle

  test_circle_constructor_setup:
    runs-on: self-hosted
    needs: test_circle_exists
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsConstructorCircle

  test_point_inside_rectangle_exists:
    runs-on: self-hosted
    needs: test_rectangle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsIsPointInsideRectangle

  test_point_inside_circle_exists:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsIsPointInsideCircle

  test_get_perimeter_rectangle_exists:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsGetPerimeterRectangle

  test_get_area_rectangle_exists:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest existsGetAreaRectangle

  test_point_on_edge_rectangle:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest isPointInsideRectangleEdges

  test_is_point_inside_rectangle:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest isPointInsideRectangleInside

  test_point_outside_rectangle:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest isPointInsideRectangleOutside

  test_get_perimeter_rectangle:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest getPerimeterRectangle

  test_get_area_rectangle:
    runs-on: self-hosted
    needs: test_circle_constructor_setup
    defaults:
      run:
        working-directory: ~/github_actions_cache/$GITHUB_REPOSITORY/Shapes/src

    steps:

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/github_actions_cache
          key: $GITHUB_REPOSITORY
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest getAreaRectangle 
