name: Test_Shapes_First_Submission

on:
  workflow_dispatch:
  
  push: 
    branches: [ main, master ]

jobs:

  test_repository_setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test Shapes directory
        run: cd Shapes

      - name: Test src directory
        run: |
          cd Shapes
          cd src
  test_compilation:
    runs-on: ubuntu-latest
    
    needs: test_repository_setup

    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2
      
      - name: Download jar files
        run: |
          wget -O processing_core.jar "https://github.com/Nathaniel-github/APCSActionTesting/blob/main/jars/processing_core.jar?raw=true"
          wget -O kTesting.jar "https://github.com/kchandra423/KTesting/blob/master/out/artifacts/KTesting_jar/KTesting.jar?raw=true"
          wget -O ShapesTest.java "https://raw.githubusercontent.com/Nathaniel-github/APCSActionTesting/main/ShapesLab/src/ShapesTest.java"
      
      - uses: actions/upload-artifact@master
        with:
          name: testing-artifacts
          path: |
            ./Shapes/src/processing_core.jar
            ./Shapes/src/kTesting.jar
            ./Shapes/src/ShapesTest.java
      
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
          
  test_constructor_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test constructor
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_constructor
  test_setPoint2_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test setPoint2
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_setPoint2

  test_draw_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test draw
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_draw

  test_getIntersectionX_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test getIntersectionX
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_getIntersectionX

  test_getIntersectionY_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test getIntersectionY
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_getIntersectionY

  test_intersects_setup:
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test intersects
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest exists_intersects

  test_vertical_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src

      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test vertical lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest vertical
          
  test_parallel_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test parallel lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest parallel
    
  test_intersecting_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test intersecting lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest intersecting

  test_non_intersecting_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test non-intersecting lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest non_intersecting
        
  test_collinear_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test collinear lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest collinear

  test_horizontal_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test horizontal lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest horizontal

  test_horizontal_and_vertical_lines:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test horizontal and vertical lines
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest "horizontal and vertical"

  test_reversed_point_collisions:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test reversed point collisions
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest "reversed points"

  test_point_collision:

    runs-on: ubuntu-latest
    needs: [test_constructor_setup, test_setPoint2_setup, test_draw_setup, test_getIntersectionX_setup, test_getIntersectionY_setup, test_intersects_setup]
    defaults:
      run:
        working-directory: ./Shapes/src

    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: testing-artifacts
          path: ./Shapes/src
          
      - name: Compile the code
        run: javac -cp .:processing_core.jar:kTesting.jar *.java
        
      - name: Test point collisions
        run: java -cp .:processing_core.jar:kTesting.jar ShapesTest point
